// <auto-generated />
namespace frontend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Smurf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Smurf));
        
        string IMigrationMetadata.Id
        {
            get { return "201212291848219_Smurf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
