// <auto-generated />
namespace frontend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixSuccesfultypo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixSuccesfultypo));
        
        string IMigrationMetadata.Id
        {
            get { return "201301011654095_Fix Succesful typo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
